server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.141.139:18761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
    shutdown:
      enabled: false
  metrics:
    tags:
      application: "${spring.application.name}"

spring:
  application:
    name: cloud-user
  profiles:
    active: peer2

---
spring:
  profiles: peer1


---
spring:
  profiles: peer2

